apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: sample
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        ports:
          - containerPort: 80
        volumeMounts:
          - name: azure
            mountPath: C:\aditya
            subPath: folder1
      volumes:
      - name: azure
        persistentVolumeClaim:
          claimName: azurefile
  selector:
    matchLabels:
      app: sample

